version: "3.8"
services:
  db:
    image: postgres:16.1
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: techuser
      POSTGRES_PASSWORD: strpass@tech

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: techuser@tech.com
      PGADMIN_DEFAULT_PASSWORD: mystrpass